[package]
license = "Apache-2.0"
name = "ainxt-update"
version = "0.1.220-alpha.4"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
dunce = { workspace = true }
ed25519-dalek = "2"
futures = { workspace = true }
indicatif = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["fs", "process", "io-util", "macros", "time"] }
tracing = { workspace = true }
ainxt-shell = { workspace = true }
ainxt-tools = { workspace = true }
ainxt-version = { workspace = true }

[dev-dependencies]
semver = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
time = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread", "test-util"] }
wiremock = { workspace = true }
